import locales from '~/data/locales.json'
import source from '~/data/content/en.json'
import { localize } from '~/data/content/flatten'

// One flat { path: text } file per language, generated by `pnpm translate`.
const translations = import.meta.glob('../data/content/translations/*.json', { eager: true, import: 'default' })

// English is the source of truth; other languages are English with translations applied on top.
const content = Object.fromEntries(locales.map(({ code }) => [
  code,
  localize(source, translations[`../data/content/translations/${code}.json`]),
]))

// Copy for the active language, e.g. `const c = useSiteContent()` then `c.nav.about` in templates.
export function useSiteContent() {
  const { locale } = useI18n()
  return computed(() => content[locale.value] ?? content.en)
}
